### ISSUE TITLE
Is there still a plan for release?

### ISSUE THREAD

**Issue by fjebaker** [cjtaylor1990/fenrir_public#1]
Hi @cjtaylor1990 ! I understand this is some years ago, but is there any plan to still release the Fenrir source? We've been working on recreating some of the thick disc reflection and reverberation models using our code, and it would be incredibly useful for us to understand how you approached certain problems, so we can sanity check some of our methods.

Thanks :)

**Comment by cjtaylor1990** [comment]
@fjebaker Thanks for reaching out. I actually just released the archived code base here: https://github.com/cjtaylor1990/fenrir/tree/main

It is a bit of a mess, since I was an overly busy graduate student, but I thought it would be better to just release everything as-is.
